val abap : string
val actionscript_3 : string
val ada : string
val angular_expression : string
val angular_html : string
val angular_inline_style : string
val angular_inline_template : string
val angular_let_declaration : string
val angular_template : string
val angular_template_blocks : string
val angular_ts : string
val apache : string
val apex : string
val apl : string
val applescript : string
val ara : string
val asciidoc : string
val asm : string
val astro : string
val awk : string
val ballerina : string
val bat : string
val beancount : string
val berry : string
val bibtex : string
val bicep : string
val bird2 : string
val blade : string
val bsl : string
val c : string
val c3 : string
val cadence : string
val cairo : string
val clarity : string
val clojure : string
val cmake : string
val cobol : string
val codeowners : string
val codeql : string
val coffee : string
val common_lisp : string
val coq : string
val cpp : string
val cpp_macro : string
val cram : string
val crystal : string
val csharp : string
val css : string
val csv : string
val cue : string
val cypher : string
val d : string
val dart : string
val dax : string
val desktop : string
val diff : string
val dockerfile : string
val dotenv : string
val dream_maker : string
val dune : string
val edge : string
val elixir : string
val elm : string
val emacs_lisp : string
val erb : string
val erlang : string
val es_tag_css : string
val es_tag_glsl : string
val es_tag_html : string
val es_tag_sql : string
val es_tag_xml : string
val fennel : string
val fish : string
val fluent : string
val fortran_fixed_form : string
val fortran_free_form : string
val fsharp : string
val gdresource : string
val gdscript : string
val gdshader : string
val genie : string
val gherkin : string
val git_commit : string
val git_rebase : string
val gleam : string
val glimmer_js : string
val glimmer_ts : string
val glsl : string
val gn : string
val gnuplot : string
val go : string
val graphql : string
val groovy : string
val hack : string
val haml : string
val handlebars : string
val haskell : string
val haxe : string
val hcl : string
val hjson : string
val hlsl : string
val html : string
val html_derivative : string
val http : string
val hurl : string
val hxml : string
val hy : string
val imba : string
val ini : string
val java : string
val javascript : string
val jinja : string
val jinja_html : string
val jison : string
val json : string
val json5 : string
val jsonc : string
val jsonl : string
val jsonnet : string
val jssm : string
val jsx : string
val julia : string
val just : string
val kdl : string
val kotlin : string
val kusto : string
val latex : string
val lean : string
val less : string
val liquid : string
val llvm : string
val log : string
val logo : string
val lua : string
val luau : string
val makefile : string
val markdown : string
val markdown_nix : string
val markdown_vue : string
val marko : string
val matlab : string
val mdc : string
val mdx : string
val menhir : string
val mermaid : string
val mipsasm : string
val mlx : string
val mojo : string
val moonbit : string
val move : string
val narrat : string
val nextflow : string
val nextflow_groovy : string
val nginx : string
val nim : string
val nix : string
val nushell : string
val objective_c : string
val objective_cpp : string
val ocaml : string
val ocamllex : string
val odin : string
val opam : string
val openscad : string
val pascal : string
val perl : string
val php : string
val pkl : string
val plsql : string
val po : string
val polar : string
val postcss : string
val powerquery : string
val powershell : string
val prisma : string
val prolog : string
val proto : string
val pug : string
val puppet : string
val purescript : string
val python : string
val qml : string
val qmldir : string
val qss : string
val r : string
val racket : string
val raku : string
val razor : string
val reason : string
val reg : string
val regexp : string
val rel : string
val riscv : string
val ron : string
val rosmsg : string
val rst : string
val ruby : string
val rust : string
val sas : string
val sass : string
val scala : string
val scheme : string
val scss : string
val sdbl : string
val shaderlab : string
val shellscript : string
val shellsession : string
val smalltalk : string
val solidity : string
val soy : string
val sparql : string
val splunk : string
val sql : string
val ssh_config : string
val stata : string
val stylus : string
val surrealql : string
val svelte : string
val swift : string
val system_verilog : string
val systemd : string
val talonscript : string
val tasl : string
val tcl : string
val templ : string
val terraform : string
val tex : string
val toml : string
val ts_tags : string
val tsv : string
val tsx : string
val turtle : string
val twig : string
val typescript : string
val typespec : string
val typst : string
val v : string
val vala : string
val vb : string
val verilog : string
val vhdl : string
val viml : string
val vue : string
val vue_directives : string
val vue_html : string
val vue_interpolations : string
val vue_sfc_style_variable_injection : string
val vue_vine : string
val vyper : string
val wasm : string
val wenyan : string
val wgsl : string
val wikitext : string
val wit : string
val wolfram : string
val xml : string
val xsl : string
val yaml : string
val zenscript : string
val zig : string

val all : (string * string) list
val available : string list
val find : string -> string option
